name: Deploy manually

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: client-pnpm-cache
        with:
          path: "node_modules"
          key: client-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.25.0
      - name: install
        run: |
          pnpm install
      - name: build
        run: |
          pnpm build
      - name: copy
        run: cp -f -r ./blog/ ./jekyll/_posts/
      - uses: actions/jekyll-build-pages@v1.0.6
        id: build-jekyll
        with:
          source: ./jekyll
          destination: ./build/blog/
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
