name: Deploy

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: client-pnpm-cache
        with:
          path: "node_modules"
          key: client-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.25.0
      - name: install
        run: |
          pnpm install
      - name: build
        run: |
          pnpm build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build